### ISSUE TITLE
Different separator?

### ISSUE THREAD

**Issue by aaltat** [boakley/brackets-robotframework#15]
Instead of using pipe as a separator, is it possible to use spaces as a separator?

**Comment by boakley** [comment]
Support for space-separated format is available starting with version 1.2 of the extension. Implementation is spread over several changesets, starting with 46635d93ce44f1869751e579206a353e80ccdec4

**Comment by boakley** [comment]
Support for space-separated format is available starting with version 1.2 of the extension. Implementation is spread over several changesets, starting with 46635d93ce44f1869751e579206a353e80ccdec4
