### ISSUE TITLE
MarkDown files (*.md) support?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [boakley/brackets-robotframework#29]
Is it possible to apply robot syntaxhighlighting on  `.md` files? I couldn't find anything in the settings.

I have robot code blocks (` ```robot` or ` ```robotframework`) in MardDown files which I would like to have syntax highlight same way as it applys to `.robot` files.

## Example:  Robot_Test_Suite.md 

```markdown
    # Executable Robot Framework Test Documenation

    This is an example of executable Robot Framework test data/documentation in a MarkDown (`.md`) file format.  Keep all your test automation assets in one place. This is almost real **SSOF** (_Single Source of Truth_), **SPOT** (_Single Point of Truth_) or call it what you like - it's just cool!


    ## Section I
    Let's start with a simple `log` test case.

    EXECUABLE ROBOT DATA I
    --------------------------------------------------

    ```robot
    *** Settings ***
    Library    Collections

    *** Test Cases ***
    001 Simple Log Test Case
        Log    Hello Python!
        Log Many          Robot  Framework  Rules!!!
    ```

    ## Section II
    Let's organize our tasks, todo and what else ...

    ### Ordered Lists

        1. Test Step äää ÄÄÄ üüü ÜÜÜÜ ßßß
           No problems with Umlauten thanks to UTF-8 encoding and Python 3
        2. Test Step
        3. Test Step

    ### Unordered Lists

        * `mkdocs new [dir-name]` - Create a new project.
        * `mkdocs serve` - Start the live-reloading docs server.
        * `mkdocs build` - Build the documentation site.
        * `mkdocs help` - Print this help message.

    ### TODOs

        * [ ] Task 001
        * [ ] Task 002
        * [x] Task 003 (done)
        * [x] ~Task 003 (totally done)~

    ### Images

    You can make beautiful documentation with images, screenshots, etc. ...

    ![Python_Logot](https://github.com/Tset-Noitamotua/_learnpython/raw/master/images/python_logo.png)

    ### (Python) Code Examples

    Have you written a custom RF Library? Document code examples here!

    ```python
    def my_function(args):
        print('Damn Sexy Python Code!')
    ```

    EXECUABLE ROBOT DATA II
    --------------------------------------------------

    ```robotframework
    *** Settings ***
    Library    Collections

    *** Test Cases ***
    002 Easy Robot Test
        Log    Hello Python!
        Log Many          Robot  Framework  Rules!!!
    ```

    ## Subtitle III

    some text
    some more text
    - foo
    - bar
```

**Comment by boakley** [comment]
No, it's possible with the current version of the robot framework brackets
plugin. Robot doesn't support files with the .md extension so it's not
supported in the plugin.

**Comment by Tset-Noitamotua** [comment]
> Robot doesn't support files with the .md extension

not yet - but I am working on a [solution ](https://github.com/Tset-Noitamotua/_learnpython/blob/master/playground/rf_scanner.py) :)

You may try it. All you need is
1. [rf_scanner.py](https://github.com/Tset-Noitamotua/_learnpython/blob/master/playground/rf_scanner.py) and[ example_01.md](https://github.com/Tset-Noitamotua/_learnpython/blob/master/playground/example_01.md) from [here](https://github.com/Tset-Noitamotua/_learnpython/tree/master/playground) (and **Python 3**).
2. run `python rf_scanner.py example_01.md` --> creates robot_data.robot
3. run `robot robot_data.robot`

Also look how beatiful test documentation can be: [example_02.md](https://github.com/Tset-Noitamotua/_learnpython/blob/master/playground/example_02.md)

**Comment by Tset-Noitamotua** [comment]
Which file extensions does your plugin looks for? Cant't I tell it somewhere in code to treat `.md` extension equally to `.robot`?

**Comment by boakley** [comment]
I am sorry I didn't respond earlier. The extension doesn't look for any file extension, this is all managed by brackets. You can tell it to open any extension in any mode you want.  This might provide a little extra insight: http://stackoverflow.com/a/21867052/7432

I doubt it will work very good to associate .md files with the robot extension. The extension makes a lot of assumptions about each line. It can probably handle the highlighting of variables, but I'm not sure if much else will work.

**Comment by Tset-Noitamotua** [comment]
Hey, thanks for the hint. I totally forgot that one can switch languages in brackets.
Actually it looks not bad. I can switch between MarkDown and Robot syntax, depending on which part I want to focus on. I think this can even be regarded as a feature - not as a workaround :)))))

![image](https://cloud.githubusercontent.com/assets/5635462/22435799/c600c42e-e721-11e6-8401-40b4246d4aa9.png)

Cheers
Tset
